### ISSUE TITLE
Integration does not acknowledge Ref_id

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-costco#10]
We have a recent test lead from Costco, where they are sending &Ref_id=1234. This isn't routing to the internal field we have designated, which is 'reference'.

Example:

```
POST /flows/54623d1a688339536438f622/sources/5419e133852bc7460e27745d/submit HTTP/1.0
Accept: */*
Connection: close
Content-Length: 410
Content-Type: application/x-www-form-urlencoded
Host: leadconduit_next_upstream
X-Forwarded-For: 204.93.149.17, 75.126.138.135
X-Forwarded-Proto: https

First_Name=TEST&Last_Name=TEST&Address=TEST1234&City=TESTHouston&State=TX&Zip=77015&Email_Address=glen%40test.com&Day_Phone=8322982222&Evening_Phone=8322981111&Membership_ID=TESTID&Loan_Type=Refinance&Credit_Score=Poor&Property_Type=Single+Family+Residence&Loan_Amount=300000&Property_Value=250000&Mortgage_Balance=0&First_Mortgage_Rate=0&LTV=80&Date+Created=2013-10-17+11%3A21%3A00&Ref_id=1234
```

This is a critical fix, as the integration is not complete without this field. Clients cannot track without this ID.

**Comment by kcaponeAP** [comment]
Need to continue this conversation. Costco is sending solely Ref_Id at this time. Can we add support to the integration to route this to our 'reference' field? This is for the Leadscon push. We have no users live on this integration at this time.

**Comment by cgrayson** [comment]
Sure thing. To be clear, is it `Ref_id`, or `Ref_Id`?

**Comment by cgrayson** [comment]
Nm :-)
