### ISSUE TITLE
Costco_Membership_Type Issue

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-costco#18]
This field is not being picked up by the intergration: Costco_Member_Type=Executive

I have verified on staging that this is missing ATM

https://next.staging.leadconduit.com/events/54e645014428bae258a0cc4f?event_id=54e645024428bae258a0cc59

Under the M account

**Comment by zalary** [comment]
I would argue that they should leads in the format that match their docs, but it would be a waste a breath

**Comment by kcaponeAP** [comment]
+1 then .. my eyes need a reboot. Tyvm!
