### ISSUE TITLE
The mortgage.first_mortgage_balance field is not populated

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-integration-costco#20]
When Costco submits `First_Mortgage_Balance=100000`, the corresponding LeadConduit field is not populated.

The problem is here: https://github.com/activeprospect/leadconduit-integration-costco/blob/master/src/inbound.coffee#L95

**Comment by zalary** [comment]
sorry @ros3bud didn't see you were assigned to this before i changed it :(

**Comment by ros3bud** [comment]
Completely ok!

**Comment by cgrayson** [comment]
Should this have been closed before PR #21 was merged?
