### ISSUE TITLE
Add additional acceptance criteria to Military

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-costco#22]
Please add the following:

RegularMilitary
No
YesRegular
YesGuardReserve

@ros3bud - we need to find out a little bit more info on this. not sure if we should do value translations or just convert the values into true / false. will update shortly.

**Comment by ros3bud** [comment]
Values should be converted to True / False as follows:

RegularMilitary --> True
No --> False
YesRegular --> True
YesGuardReserve --> False

**Comment by ros3bud** [comment]
Confirmed that true and false will not be sent - only the values on the left.

**Comment by kcaponeAP** [comment]
Please note one data change:

RegularMilitary --> True
No --> False
YesRegular --> True
YesGuardReserve --> True ---> CHANGE

**Comment by ros3bud** [comment]
Noted.

**Comment by ros3bud** [comment]
@kcaponeAP - this is all set.

**Comment by zalary** [comment]
it may be disingenuous to say this is all set unless this has been deployed to production. (maybe it has been and I don't know that)
but otherwise she still won't see this behavior in the app.

**Comment by ros3bud** [comment]
Makes sense, Zal. Thanks for pointing that out.

**Comment by cgrayson** [comment]
Good point, Zal. And reminds me: we haven't done this very consistently but we should try to do better - putting the integration version number that contains the fix here in the issue. That makes it possible for users to check against what's deployed (per http://docs.leadconduit.com). Also, once [client issue 645](https://github.com/activeprospect/leadconduit-client/issues/645) is implemented, that version number will be visible on each event.

**Comment by ros3bud** [comment]
Fixed in Version 0.0.16.
