### ISSUE TITLE
Please add Property_Use / PropertyUse to integration

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-costco#23]
Costco is now sending PropertyUse. Please add this to the integration. Since they change around their POSTs so often, please allow this to accept PropertyUse.

Sample lead here:
https://next.leadconduit.com/events/54fdf23d356ea6d906997a88

CW account.

**Comment by ros3bud** [comment]
Edit: 
Since they change around their POSTs so often, please allow this to also accept Property_Use - which they occasionally send for the same data interchangeably.

**Comment by zalary** [comment]
That event doesn't seem to work for me.   I checked several Costco events and do not see any using PropertyUse or or Property_Use.  Do you have another example?

**Comment by kcaponeAP** [comment]
PropertyUse:

https://next.leadconduit.com/events/54ff20b61a80aa8c0e086a5f

Flow belongs to client P

**Comment by kcaponeAP** [comment]
Costco is live with this client ATM so we request this to be fixed this week.

**Comment by alexkwolfe** [comment]
@ros3bud, is this in progress?

**Comment by ros3bud** [comment]
Yes

**Comment by ros3bud** [comment]
Awaiting an answer regarding the possible values for this field. Need to confirm whether they are expecting "primary, secondary, or investment."

**Comment by kcaponeAP** [comment]
I've got to do a little more research on this issue with the client. it appears that single family is hard coded into their request for just one client.

**Comment by ros3bud** [comment]
Closing the issue for now as this is no longer needed per K. @kcaponeAP please reopen if necessary.

**Comment by kcaponeAP** [comment]
Legacy field. Will not need to add.
