### ISSUE TITLE
New Costco fields

### ISSUE THREAD

**Issue by alexj** [activeprospect/leadconduit-integration-costco#33]
Jonathan, could you please add these fields to the Costco integration in the next day or two?
* `mortgage.bankruptcy.was_declared` - existing standard field that we need to ensure we're capturing
* `mortgage.bankruptcy.date_declared` - new standard date field (Costco will send `12/23/2005`)
* `costco.income_verification` - boolean (`Yes` or `No`)
* `costco.mortgage.late_payments` - string (`Not Applicable`, `0`,`1`, `1or 2`, `2 or more`, `3 or more`)
* `costco.mortgage.short_sale` - boolean (`Yes` or `No`)

**Comment by jgrayson676** [comment]
Do you know what Costco calls those fields?

**Comment by alexj** [comment]
Sorry, I just saw this question. They should send those fields (they asked us to provide them).
